name: Cypress Tests

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        env:
          CYPRESS_USER1: ${{ secrets.USER1 }}
          CYPRESS_PASSWORD1: ${{ secrets.PASSWORD1 }}
          CYPRESS_USER2: ${{ secrets.USER2 }}
          CYPRESS_PASSWORD2: ${{ secrets.PASSWORD2 }}
        run: npx cypress run